apiVersion: v1
kind: Service
metadata:
  name: legacy-iris
  labels:
    app.kubernetes.io/name: legacy-iris
spec:
  selector:
    app.kubernetes.io/name: legacy-iris
  ports:
    - {name: superserver, port: 1972, targetPort: superserver}
    - {name: web, port: 52773, targetPort: web}
